image: webdevops/php-dev:8.0

cache:
    paths:
        - ./vendor/
        - ./tools/php-cs-fixer/vendor/

before_script:
    - apt update && apt install -y software-properties-common gcc-8
    - add-apt-repository ppa:ubuntu-toolchain-r/test
    - apt update && apt install -y wget pkg-config cmake git && apt install --only-upgrade libstdc++6
    - wget https://raw.githubusercontent.com/php-opencv/php-opencv-packages/master/opencv_4.5.0_amd64.deb && dpkg -i opencv_4.5.0_amd64.deb && rm opencv_4.5.0_amd64.deb
    - git clone https://github.com/php-opencv/php-opencv.git
    - cd php-opencv && phpize && ./configure && make && make install
    - cd ../ && rm -rf php-opencv
    - echo "extension=opencv.so" >> /opt/docker/etc/php/php.ini
    - composer install --prefer-dist --no-ansi --no-interaction --no-progress
    - composer install --working-dir=tools/php-cs-fixer --prefer-dist --no-ansi --no-interaction --no-progress

stages:
    - analyse
    - test

analyse:
    stage: analyse
    script:
        - vendor/bin/phpstan analyse
        - tools/php-cs-fixer/vendor/bin/php-cs-fixer fix ./ --dry-run --diff

test:
    stage: test
    script:
        - vendor/bin/phpunit --coverage-text --colors=never tests