image: jitesoft/composer:8

cache:
    paths:
        - ./vendor/

before_script:
    - composer install --prefer-dist --no-ansi --no-interaction --no-progress

stages:
    - phpunit

lint:
    stage: lint
    script:
        - composer lint

phpunit:
    stage: phpunit
    before_script:
        - composer install --prefer-dist --no-ansi --no-interaction --no-progress
    script:
        - vendor/bin/phpunit --coverage-text --colors=never tests