image: webdevops/php-dev:8.0-alpine

cache:
    paths:
        - ./vendor/

before_script:
    - composer install --prefer-dist --no-ansi --no-interaction --no-progress

stages:
    - analyse
    - test

analyse:
    stage: analyse
    script:
        - vendor/bin/phpstan analyse

test:
    stage: test
    script:
        - vendor/bin/phpunit --coverage-text --colors=never tests