image: jitesoft/phpunit:8.0

cache:
    paths:
        - ./vendor/
        - ./tools/php-cs-fixer/vendor/

before_script:
    - apk update && apk add libgit2-dev git opencv=4.5.2-r0
    - python3 -c "import cv2; print(cv2.__version__)"
    - git clone https://github.com/php-opencv/php-opencv.git
    - cd php-opencv
    - phpize
    - ./configure --with-php-config=/usr/bin/php-config
    - make
    - make install
    - cd ../
    - rm -rf php-opencv
    - echo "extension=opencv.so" > /etc/php/8.0/cli/conf.d/opencv.ini
    - composer install --prefer-dist --no-ansi --no-interaction --no-progress
    - composer install --working-dir=tools/php-cs-fixer --prefer-dist --no-ansi --no-interaction --no-progress

stages:
    - analyse
    - test

analyse:
    stage: analyse
    script:
        - vendor/bin/phpstan analyse
        - tools/php-cs-fixer/vendor/bin/php-cs-fixer fix ./ --dry-run --diff

test:
    stage: test
    script:
        - vendor/bin/phpunit --coverage-text --colors=never tests